### ISSUE TITLE
error: use of undeclared identifier 'kAudioUnitProperty_LastRenderSampleTime'; did you mean 'kAudioUnitProperty_LastRenderError'?

### ISSUE THREAD

**Issue by mightgoyardstill** [Tremus/CPLUG#6]
just trying to run the cmake to build the project example but for some reason i get this error
`error: use of undeclared identifier 'kAudioUnitProperty_LastRenderSampleTime'; did you mean 'kAudioUnitProperty_LastRenderError'?
[build]     case kAudioUnitProperty_LastRenderSampleTime:
[build]          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build]          kAudioUnitProperty_LastRenderError
[build] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioUnitProperties.h:797:2: note: 'kAudioUnitProperty_LastRenderError' declared here
[build]         kAudioUnitProperty_LastRenderError                              = 22,
[build]         ^
[build] 1 error generated.`

from this bit of code in the cplug_auv2.c file:
`    case kAudioUnitProperty_LastRenderSampleTime:
        CPLUG_LOG_ASSERT_RETURN(inScope == kAudioUnitScope_Global, kAudioUnitErr_InvalidScope);
        CPLUG_SAFE_SET_PTR(outDataSize, sizeof(Float64));
        break;`
        
at line 395

**Comment by Tremus** [comment]
I see you're using the MacOSX 11 SDK. This enum is macOS 12+ ([apple docs](https://developer.apple.com/documentation/audiotoolbox/1534199-general_audio_unit_properties/kaudiounitproperty_lastrendersampletime
))

I've removed the line in this commit 0e5ee952209bbe0eadffd3d52d5a395166776886 which should fix your problem. It wasn't being used anyway, and hosts don't seem to ask for it, at least in the example plugin.
